# Generated automatically from Make-in by configure.
# Makefile for program source directory in GNU NLS utilities package.
# Copyright (C) 1995, 1996, 1997 by Ulrich Drepper <drepper@gnu.ai.mit.edu>
#
# This file file be copied and used freely without restrictions.  It can
# be used in projects which are not available under the GNU Public License
# but which still want to provide support for the GNU gettext functionality.
# Please note that the actual code is *not* freely available.

PACKAGE = bfd
VERSION = 2.9.5

SHELL = /bin/sh


srcdir = .
top_srcdir = ..

prefix = /home/zhoutao/Desktop/Arch
exec_prefix = ${prefix}
datadir = $(prefix)/share
localedir = $(datadir)/locale
gnulocaledir = $(prefix)/share/locale
gettextsrcdir = $(prefix)/share/gettext/po
subdir = po

INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
MKINSTALLDIRS = $(srcdir)/../../mkinstalldirs

CC = gcc
GENCAT = @GENCAT@
GMSGFMT = PATH=../src:$$PATH /usr/bin/msgfmt
MSGFMT = /usr/bin/msgfmt
XGETTEXT = PATH=../src:$$PATH /usr/bin/xgettext
MSGMERGE = PATH=../src:$$PATH msgmerge

DEFS = -DHAVE_CONFIG_H
CFLAGS = -g -O2 -W -Wall
CPPFLAGS = 

INCLUDES = -I.. -I$(top_srcdir)/intl

COMPILE = $(CC) -c $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) $(XCFLAGS)

SOURCES = cat-id-tbl.c
POFILES = 
GMOFILES = 
DISTFILES = ChangeLog Makefile.in.in POTFILES.in $(PACKAGE).pot \
stamp-cat-id $(POFILES) $(GMOFILES) $(SOURCES)

POTFILES = \
	../aix386-core.c \
	../aout-adobe.c \
	../aout-arm.c \
	../aout-ns32k.c \
	../aout-sparcle.c \
	../aout-target.h \
	../aout-tic30.c \
	../aout0.c \
	../aout32.c \
	../aout64.c \
	../aoutf1.h \
	../aoutx.h \
	../archive.c \
	../archures.c \
	../bfd.c \
	../binary.c \
	../bout.c \
	../cache.c \
	../cf-i386lynx.c \
	../cf-m68klynx.c \
	../cf-sparclynx.c \
	../cisco-core.c \
	../coff-a29k.c \
	../coff-alpha.c \
	../coff-apollo.c \
	../coff-arm.c \
	../coff-aux.c \
	../coff-go32.c \
	../coff-h8300.c \
	../coff-h8500.c \
	../coff-i386.c \
	../coff-i860.c \
	../coff-i960.c \
	../coff-m68k.c \
	../coff-m88k.c \
	../coff-mips.c \
	../coff-pmac.c \
	../coff-rs6000.c \
	../coff-sh.c \
	../coff-sparc.c \
	../coff-stgo32.c \
	../coff-svm68k.c \
	../coff-tic30.c \
	../coff-tic80.c \
	../coff-u68k.c \
	../coff-w65.c \
	../coff-we32k.c \
	../coff-z8k.c \
	../coffcode.h \
	../coffgen.c \
	../cofflink.c \
	../coffswap.h \
	../corefile.c \
	../cpu-a29k.c \
	../cpu-alpha.c \
	../cpu-arc.c \
	../cpu-arm.c \
	../cpu-d10v.c \
	../cpu-d30v.c \
	../cpu-fr30.c \
	../cpu-h8300.c \
	../cpu-h8500.c \
	../cpu-hppa.c \
	../cpu-i386.c \
	../cpu-i860.c \
	../cpu-i960.c \
	../cpu-m10200.c \
	../cpu-m10300.c \
	../cpu-m32r.c \
	../cpu-m68k.c \
	../cpu-m88k.c \
	../cpu-mcore.c \
	../cpu-mips.c \
	../cpu-ns32k.c \
	../cpu-powerpc.c \
	../cpu-rs6000.c \
	../cpu-sh.c \
	../cpu-sparc.c \
	../cpu-tic30.c \
	../cpu-tic80.c \
	../cpu-v850.c \
	../cpu-vax.c \
	../cpu-w65.c \
	../cpu-we32k.c \
	../cpu-z8k.c \
	../demo64.c \
	../dwarf2.c \
	../ecoff.c \
	../ecofflink.c \
	../ecoffswap.h \
	../elf-bfd.h \
	../elf-m10200.c \
	../elf-m10300.c \
	../elf.c \
	../elf32-arc.c \
	../elf32-d10v.c \
	../elf32-d30v.c \
	../elf32-fr30.c \
	../elf32-gen.c \
	../elf32-hppa.c \
	../elf32-hppa.h \
	../elf32-i386.c \
	../elf32-i860.c \
	../elf32-i960.c \
	../elf32-m32r.c \
	../elf32-m68k.c \
	../elf32-m88k.c \
	../elf32-mcore.c \
	../elf32-mips.c \
	../elf32-ppc.c \
	../elf32-sh.c \
	../elf32-sparc.c \
	../elf32-v850.c \
	../elf32.c \
	../elf64-alpha.c \
	../elf64-gen.c \
	../elf64-mips.c \
	../elf64-sparc.c \
	../elf64.c \
	../elfarm-nabi.c \
	../elfarm-oabi.c \
	../elfcode.h \
	../elflink.c \
	../format.c \
	../genlink.h \
	../go32stub.h \
	../hash.c \
	../hp300bsd.c \
	../hp300hpux.c \
	../hppa_stubs.h \
	../hpux-core.c \
	../i386aout.c \
	../i386bsd.c \
	../i386dynix.c \
	../i386freebsd.c \
	../i386linux.c \
	../i386lynx.c \
	../i386mach3.c \
	../i386msdos.c \
	../i386netbsd.c \
	../i386os9k.c \
	../ieee.c \
	../ihex.c \
	../init.c \
	../irix-core.c \
	../libaout.h \
	../libbfd.c \
	../libbfd.h \
	../libcoff.h \
	../libecoff.h \
	../libhppa.h \
	../libieee.h \
	../libnlm.h \
	../liboasys.h \
	../linker.c \
	../lynx-core.c \
	../m68k4knetbsd.c \
	../m68klinux.c \
	../m68klynx.c \
	../m68knetbsd.c \
	../m88kmach3.c \
	../mipsbsd.c \
	../netbsd.h \
	../newsos3.c \
	../nlm-target.h \
	../nlm.c \
	../nlm32-alpha.c \
	../nlm32-i386.c \
	../nlm32-ppc.c \
	../nlm32-sparc.c \
	../nlm32.c \
	../nlm64.c \
	../nlmcode.h \
	../ns32k.h \
	../ns32knetbsd.c \
	../oasys.c \
	../opncls.c \
	../osf-core.c \
	../pc532-mach.c \
	../pe-arm.c \
	../pe-i386.c \
	../pe-mcore.c \
	../pe-ppc.c \
	../pei-arm.c \
	../pei-i386.c \
	../pei-mcore.c \
	../pei-ppc.c \
	../ppcboot.c \
	../reloc.c \
	../reloc16.c \
	../riscix.c \
	../sco5-core.c \
	../section.c \
	../som.c \
	../som.h \
	../sparclinux.c \
	../sparclynx.c \
	../sparcnetbsd.c \
	../srec.c \
	../stab-syms.c \
	../stabs.c \
	../sunos.c \
	../syms.c \
	../targets.c \
	../tekhex.c \
	../trad-core.c \
	../vaxnetbsd.c \
	../versados.c \
	../vms-gsd.c \
	../vms-hdr.c \
	../vms-misc.c \
	../vms-tir.c \
	../vms.c \
	../vms.h \
	../xcofflink.c

CATALOGS = 
CATOBJEXT = .gmo
INSTOBJEXT = .mo

.SUFFIXES:
.SUFFIXES: .c .o .po .pox .gmo .mo .msg .cat

.c.o:
	$(COMPILE) $<

.po.pox:
	$(MAKE) $(PACKAGE).pot
	$(MSGMERGE) $< $(srcdir)/$(PACKAGE).pot -o $*.pox

.po.mo:
	$(MSGFMT) -o $@ $<

.po.gmo:
	file=$(srcdir)/`echo $* | sed 's,.*/,,'`.gmo \
	  && rm -f $$file && $(GMSGFMT) -o $$file $<

.po.cat:
	sed -f ../intl/po2msg.sed < $< > $*.msg \
	  && rm -f $@ && $(GENCAT) $@ $*.msg


all: all-yes

all-yes: $(CATALOGS) # $(PACKAGE).pot
all-no:

$(srcdir)/$(PACKAGE).pot: $(POTFILES)
	$(XGETTEXT) --default-domain=$(PACKAGE) --directory=$(top_srcdir) \
	  --add-comments --keyword=_ --keyword=N_ \
	  --files-from=$(srcdir)/POTFILES.in
	rm -f $(srcdir)/$(PACKAGE).pot
	mv $(PACKAGE).po $(srcdir)/$(PACKAGE).pot

$(srcdir)/cat-id-tbl.c: stamp-cat-id; @:
$(srcdir)/stamp-cat-id: $(PACKAGE).pot
	rm -f cat-id-tbl.tmp
	sed -f ../intl/po2tbl.sed $(srcdir)/$(PACKAGE).pot \
		| sed -e "s/@PACKAGE NAME@/$(PACKAGE)/" > cat-id-tbl.tmp
	if cmp -s cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; then \
	  rm cat-id-tbl.tmp; \
	else \
	  echo cat-id-tbl.c changed; \
	  rm -f $(srcdir)/cat-id-tbl.c; \
	  mv cat-id-tbl.tmp $(srcdir)/cat-id-tbl.c; \
	fi
	cd $(srcdir) && rm -f stamp-cat-id && echo timestamp > stamp-cat-id


install: install-exec install-data
install-exec:
install-info:
install-data: install-data-yes
install-data-no: all
install-data-yes: all
	if test -r $(MKINSTALLDIRS); then \
	  $(MKINSTALLDIRS) $(datadir); \
	else \
	  $(top_srcdir)/mkinstalldirs $(datadir); \
	fi
	@catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  case "$$cat" in \
	    *.gmo) destdir=$(gnulocaledir);; \
	    *)     destdir=$(localedir);; \
	  esac; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  dir=$$destdir/$$lang/LC_MESSAGES; \
	  if test -r $(MKINSTALLDIRS); then \
	    $(MKINSTALLDIRS) $$dir; \
	  else \
	    $(top_srcdir)/mkinstalldirs $$dir; \
	  fi; \
	  if test -r $$cat; then \
	    $(INSTALL_DATA) $$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $$cat as $$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  else \
	    $(INSTALL_DATA) $(srcdir)/$$cat $$dir/$(PACKAGE)$(INSTOBJEXT); \
	    echo "installing $(srcdir)/$$cat as" \
		 "$$dir/$(PACKAGE)$(INSTOBJEXT)"; \
	  fi; \
	  if test -r $$cat.m; then \
	    $(INSTALL_DATA) $$cat.m $$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	    echo "installing $$cat.m as $$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	  else \
	    if test -r $(srcdir)/$$cat.m ; then \
	      $(INSTALL_DATA) $(srcdir)/$$cat.m \
		$$dir/$(PACKAGE)$(INSTOBJEXT).m; \
	      echo "installing $(srcdir)/$$cat as" \
		   "$$dir/$(PACKAGE)$(INSTOBJEXT).m"; \
	    else \
	      true; \
	    fi; \
	  fi; \
	done
	if test "$(PACKAGE)" = "gettext"; then \
	  if test -r $(MKINSTALLDIRS); then \
	    $(MKINSTALLDIRS) $(gettextsrcdir); \
	  else \
	    $(top_srcdir)/mkinstalldirs $(gettextsrcdir); \
	  fi; \
	  $(INSTALL_DATA) $(srcdir)/Makefile.in.in \
			  $(gettextsrcdir)/Makefile.in.in; \
	else \
	  : ; \
	fi

# Define this as empty until I found a useful application.
installcheck:

uninstall:
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(localedir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT); \
	  rm -f $(gnulocaledir)/$$lang/LC_MESSAGES/$(PACKAGE)$(INSTOBJEXT).m; \
	done
	rm -f $(gettextsrcdir)/po-Makefile.in.in

check: all

cat-id-tbl.o: ../intl/libgettext.h

dvi info tags TAGS ID:

mostlyclean:
	rm -f core core.* *.pox $(PACKAGE).po *.old.po cat-id-tbl.tmp
	rm -fr *.o

clean: mostlyclean

distclean: clean
	rm -f Makefile Makefile.in POTFILES *.mo *.msg *.cat *.cat.m

maintainer-clean: distclean
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."
	rm -f $(GMOFILES)

distdir = ../$(PACKAGE)-$(VERSION)/$(subdir)
dist distdir: update-po $(DISTFILES)
	dists="$(DISTFILES)"; \
	for file in $$dists; do \
	  ln $(srcdir)/$$file $(distdir) 2> /dev/null \
	    || cp -p $(srcdir)/$$file $(distdir); \
	done

update-po: Makefile
	$(MAKE) $(PACKAGE).pot
	PATH=`pwd`/../src:$$PATH; \
	cd $(srcdir); \
	catalogs='$(CATALOGS)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
	  mv $$lang.po $$lang.old.po; \
	  echo "$$lang:"; \
	  if $(MSGMERGE) $$lang.old.po $(PACKAGE).pot -o $$lang.po; then \
	    rm -f $$lang.old.po; \
	  else \
	    echo "msgmerge for $$cat failed!"; \
	    rm -f $$lang.po; \
	    mv $$lang.old.po $$lang.po; \
	  fi; \
	done

POTFILES: POTFILES.in
	( if test 'x$(srcdir)' != 'x.'; then \
	    posrcprefix='$(top_srcdir)/'; \
	  else \
	    posrcprefix="../"; \
	  fi; \
	  rm -f $@-t $@ \
	    && (sed -e '/^#/d' -e '/^[ 	]*$$/d' \
		    -e "s@.*@	$$posrcprefix& \\\\@" < $(srcdir)/$@.in \
		| sed -e '$$s/\\$$//') > $@-t \
	    && chmod a-w $@-t \
	    && mv $@-t $@ )

POTFILES.in: # ../Makefile
	cd .. && $(MAKE) po/POTFILES.in

Makefile: Make-in ../config.status POTFILES
	cd .. \
	  && CONFIG_FILES=$(subdir)/Makefile.in:$(subdir)/Make-in \
	     CONFIG_HEADERS= $(SHELL) ./config.status

# Tell versions [3.59,3.63) of GNU make not to export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
